### ISSUE TITLE
Contribution in Lide

### ISSUE THREAD

**Issue by jhernancanom** [eugenkiss/7guis#22]
Hi, Eugen.

I want to participate with this contribution in Lide framework.

Can you include it in this portal, please?

Thanks.
[7GUIs-HCano-Lide.zip](https://github.com/eugenkiss/7guis/files/1693901/7GUIs-HCano-Lide.zip)

**HERNAN CANO M**
Systems Analyst 
Medellín, Antioquia, Colombia

**Comment by eugenkiss** [comment]
Hi @jhernancanom,

thanks for contributing! It would be awesome if you created Github repositories of your contributions and linked them here: https://github.com/eugenkiss/7guis/wiki#implementations

If you can't edit the Wiki let me know.

I hope to invest some time the next weekends to restructure this repository. The idea is to improve the presentation and make it easier/clearer how to contribute.

**Comment by jhernancanom** [comment]
Fine, Eugen.
I'll do so.

Thanks.


2018-02-06 2:18 GMT-05:00 Eugen Kiss :

**Comment by jhernancanom** [comment]
Done.


2018-02-06 2:18 GMT-05:00 Eugen Kiss:

**Comment by eugenkiss** [comment]
Hi @jhernancanom. Thanks for that!

**Comment by jhernancanom** [comment]
Hi, Eugen.

My contribution was with a total of three:  7GUIs_VFP
<https://github.com/jhernancanom/7GUIs_VFP> ,  7GUIs_Lua
<https://github.com/jhernancanom/7GUIs_Lua> , and  7GUIs_Lide
<https://github.com/jhernancanom/7GUIs_Lide>. I remember to put oll of the
three in the implementations. But I only see  7GUIs_VFP
<https://github.com/jhernancanom/7GUIs_VFP> .

Unfortunetely now I cannot edit in your portal. I am updating them.

Can you say me how to add the another two? Can you add them?

Thanks.




2018-02-07 14:37 GMT-05:00 Eugen Kiss <notifications-github.com>:

**Comment by eugenkiss** [comment]
Hi @jhernancanom,

did you see <https://eugenkiss.github.io/7guis/contributing>? Please give it a try and let me know if you get stuck so I can improve the instructions.
