### ISSUE TITLE
Website down – thesis unavailable

### ISSUE THREAD

**Issue by aspnetde** [eugenkiss/7guis#28]
Hi @eugenkiss!

I just noticed that your website is down since a couple of days, which unfortunately also lead to https://eugenkiss.com/projects/thesis.pdf not being available anymore.

Would it be possible to mirror the document somewhere else?

Thomas

**Comment by mirohs** [comment]
Unfortunately, Eugen passed away recently. I relocated the thesis to https://eugenkiss.github.io/7guis.

**Comment by aspnetde** [comment]
@mirohs That's sad news. Very sorry to hear about that :-(.

What is still missing is Eugen's thesis itself, the PDF document (which is linked for example from [here](https://github.com/eugenkiss/7guis/blob/master/site/src/containers/More.js#L7)) . I've got a copy of it. Do you think you could put it to the 7guis website as well?

(If you don't have time, I could prepare a PR)

**Comment by mirohs** [comment]
I just changed references to the thesis. Seemingly I am not able to change https://eugenkiss.github.io/7guis/more

**Comment by aspnetde** [comment]
Thanks, I got the working link out of your commit. This one I can cite.

R.I.P. Eugen

**Comment by Karkunow** [comment]
@aspnetde I was also searching for the thesis and found it using Wayback Machine:
https://web.archive.org/web/20180509155949/https://eugenkiss.com/projects/thesis.pdf
