### ISSUE TITLE
Enhancement: localization

### ISSUE THREAD

**Issue by dumblob** [eugenkiss/7guis#32]
Nowadays pretty much every GUI has to be localized. This is actually rather difficult, because simple GUI libs use the text as identifier (which becomes impossible if localized) and complex GUIs are further more complicated.

Something like a localized calculator (latin, arabic, rome, chinese, japan number systems and operation names) could be a nice showcase of the GUI library capabilities.

**Comment by egonelbre** [comment]
Things that could be tested:
* translation
* date localization
* left-to-right vs right-to-left text
* left-to-right vs right-to-left input
* BIDI input

**Comment by gjvnq** [comment]
Another important issue is collation for unicode comparisons and sorting, i.e. depending on the language of the user, two strings may or may not be equal.

This becomes incredibly important when doing searches, especially fuzzy ones.

Another, simple but important, issue is changing languages on the fly, without having to restart or reload the application.
