### ISSUE TITLE
enhancement: treeview

### ISSUE THREAD

**Issue by jlgerber** [eugenkiss/7guis#35]
Every good, complete ui toolkit needs to be able to render a tree view. It would be great to add a task that incorporates one.

**Comment by dumblob** [comment]
IMHO this is quite problematic - actually every good & complete UI toolkit does it so much differently, that I doubt the common denominator will make any sense. Is e.g. a menu with submenus a tree view? Is a mind map a tree view? Is rendering label widgets with y coordinate increased by few pixels of a depth first search a tree view? What is actually a tree view?

What does a "tree view" testify anyway? IMHO it doesn't say anything important about the UI toolkit capability. But I might be missing something, so please elaborate :wink:.
