### ISSUE TITLE
Speech-To-Text / Text-To-Speech

### ISSUE THREAD

**Issue by egonelbre** [eugenkiss/7guis#42]
Speech to text / Text to speech can be quite important for accessibility. This could be an extension to any example that contains text input.

This would test how well GUI-s integrate with accessibility features.

For all examples, except circle drawing:
* Speech-To-Text:  It should be possible to interact with the app by voice alone.
* Text-To-Speech: It should be possible to navigate the app blindfolded.

**Comment by dumblob** [comment]
I'd actually broaden the scope of this enhancement to general support for accessibility (easy font size increase, easy color management/theming, text-to-speech/speech-to-tex, etc.) and text2speech/speech2text would become just one part of this.

I'm though still unsure how to well define the test case for 7guis. Any ideas?

**Comment by egonelbre** [comment]
Ah, easy, all examples should support it. Or in other words, you can interact with full functionality without needing to use a keyboard or mouse. (Except the circle drawing example).

**Comment by egonelbre** [comment]
> I'd actually broaden the scope of this enhancement to general support for accessibility...

I think it's worthwhile to separate each accessibility feature rather than putting them altogether. From GUI framework perspective they require significantly different solutions, so many of them may support one, but not the others.
