### ISSUE TITLE
Enhanced Contrast

### ISSUE THREAD

**Issue by egonelbre** [eugenkiss/7guis#43]
This is from accessibility features. Enhanced contrast and increased font sizes are important for people with low vision. This can be introduced as either reading system settings or a separate toggle to any of the GUI-s.

In principle, it should be possible to have separate "enhanced contrast" theme without special casing every single widget.

* https://www.w3.org/TR/low-vision-needs/

**Comment by dumblob** [comment]
Oops, I've proposed a similar thing in https://github.com/eugenkiss/7guis/issues/42#issuecomment-726672433 about a minute before this issue got created :wink:.

**Comment by egonelbre** [comment]
One step could be to allow using custom font by the user. e.g. https://opendyslexic.org/
