### ISSUE TITLE
Add honorable mention: datepickers

### ISSUE THREAD

**Issue by gjvnq** [eugenkiss/7guis#49]
It may be a good idea to have some sort of honorable mentions section for tasks that don't fall totally within the 7GUIs vision but that can be good exercises.

Datepickers seem like a good candidate for evaluating GUI frameworks because or how complex yet simple they can be.

Some problems faced when writing them include:

  * The two way communication between the text field and the popup.
  * The configuration of multiple allowed time spans.
  * "Replacing" the popup when the user clicks on the year to show the list of years.
  * Not all date times are valid: some never happen because of daylight saving time and others happen twice.

**Comment by dumblob** [comment]
As I already wrote an advanced date picker after a thorough analysis of existing solutions (and it wasn't even a traditional popup as popups are a UX antipattern if not used just for the most simple stuff like few words of text) I'd counter the example of honorably mention a date picker.

In my opinion all of the above wouldn't say much more (if anything) about the UI library than what other 7GUI tasks demonstrate. 7GUI is to "show the trend" and any date picker wouldn't change this trend IMHO.

Date pickers are mostly about business logic and about screen updates, but that really doesn't contribute to the trend already established by other 7GUI tasks.
